### ISSUE TITLE
Change Owner Keys

### ISSUE THREAD

**Issue by controllinghand** [greymass/eos-voter#273] opened 2018-07-30 05:52 UTC
It would be awesome if there were a way to change your Owner Public Keys.  I have a few accounts that have the same key for Owner and Active.  And I would like to to make these accounts more secure.

Do you think you could add this feature?

Thanks,
~S

**Comment by aaroncox** [comment] 2018-07-30 21:32
It's the feature set we're working on right now (permissions/keys management). 

We are probably a week or two away from completing development/testing. It's something we want to make sure we get absolutely right - since it could cause people to lose access to their account. 

Closing this one out as a duplicate of #225 :)

**Closed by aaroncox** 2018-07-30 21:32 UTC
