### ISSUE TITLE
unable to send EOS tokens from eos-voter wallet

### ISSUE THREAD

**Issue by redeyedassassin** [greymass/eos-voter#611] opened 2019-04-27 13:37 UTC
i receive the following error when i attempt to send eos tokens i can vote but not send tokens.

![eos error](https://user-images.githubusercontent.com/50049898/56850388-dae38500-68f9-11e9-8892-4a5334db0206.png)

**Comment by Rendiesel23** [comment] 2019-04-27 15:23
I am having the same issue, its been since yesterday, i cant send my eos out of my eos-voter wallet either, whats going on?

**Comment by redeyedassassin** [comment] 2019-04-27 20:21
not sure i just downloaded scatter and made do waiting on a response

**Comment by Rendiesel23** [comment] 2019-04-27 20:44
my scatter wallet wont send either, really starting to be concerned

**Comment by aaroncox** [comment] 2019-04-27 21:11
In the upper left, does it show `accountname@active` in the dropdown, with both the account name and the permission? 

I'm not able to reproduce this issue in 0.7.6 with a fresh wallet. One thing that might fix it is if you reset the application (Tools -> Reset Application), then reimport your keys/accounts to start a new wallet. It's possible if you have an older version, one of the upgrades mangled the wallet somehow.

**Comment by Rendiesel23** [comment] 2019-04-28 00:46
ok ill try that my friend, thanks!

**Comment by aaroncox** [comment] 2019-05-03 18:14
Closing this issue out - feel free to reopen if the problem persists after reimporting.

**Closed by aaroncox** 2019-05-03 18:14 UTC
