### ISSUE TITLE
Stage #1 Connection

### ISSUE THREAD

**Issue by Bardamazon** [greymass/eos-voter#111] opened 2018-06-18 22:35 UTC
Both the link to select a server and the "Connect to Server" button do not work in stage #1 when trying to set up the EOS wallet in v.0.1.6 exe version.

**Comment by aaroncox** [comment] 2018-06-19 00:18
Duplicate of #104 and resolved in version 0.1.7 (released a few minutes ago).

**Closed by aaroncox** 2018-06-19 00:18 UTC
